imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'


stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            blameable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: LG\UserBundle\Entity\User
    from_email:
        address: noreply@toni0.com
        sender_name: MyAE
    profile:
        form:
            type: LG\UserBundle\Form\Type\ProfileFormType
            # if you are using Symfony < 2.8 you should use the type name instead
            # type: app_user_registration

knp_snappy:
    pdf:
        enabled:    true
        binary:    "/usr/bin/xvfb-run /usr/bin/wkhtmltopdf"
        options:
            no-outline: true
            encoding: UTF-8
    image:
        enabled:    true
        binary:     "/usr/bin/xvfb-run /usr/bin/wkhtmltoimage"
        options:    []


assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        js_bootstrap_and_jquery:
            inputs:
                - '../app/Resources/public/js/jquery.js'
                - '../app/Resources/public/js/bootstrap.min.js'
        js_jquery_ui:
            inputs:
                - '../app/Resources/public/js/jquery-ui.js'
        css_bootstrap:
            inputs:
                - '../app/Resources/public/css/bootstrap.min.css'
        css_bootstrap_and_sbadmin:
            inputs:
                - '../app/Resources/public/css/bootstrap.min.css'
                - '../app/Resources/public/css/sb-admin.css'
                - '../app/Resources/public/font-awesome/css/font-awesome.css'
        font-awesome-otf:
            inputs: '../app/Resources/public/font-awesome/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '../app/Resources/public/font-awesome/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '../app/Resources/public/font-awesome/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '../app/Resources/public/font-awesome/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '../app/Resources/public/font-awesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
        glyphicons-eot:
            inputs: '../app/Resources/public/fonts/glyphicons-halflings-regular.eot'
            output: 'fonts/glyphicons.eot'
        glyphicons-woff2:
            inputs: '../app/Resources/public/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons.woff2'
        glyphicons-woff:
            inputs: '../app/Resources/public/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons.woff'
        glyphicons-ttf:
            inputs: '../app/Resources/public/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons.ttf'
        glyphicons-svg:
            inputs: '../app/Resources/public/fonts/glyphicons-halflings-regular.svg'
            output: 'fonts/glyphicons.svg'


