# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        LG\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
          id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: (^/Connexion$)|(^/Reinitialisation)
            anonymous: true
            logout_on_user_change: true

        main:
            pattern:      ^/
            anonymous:    false
            provider:     main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                secret:     "%secret%" 
            logout_on_user_change: true