# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        LG\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          id: fos_user.user_provider.username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false

        main_login:
            pattern: (^/Connexion$)|(^/Reinitialisation)
            anonymous: true

        main:
            pattern:      ^/
            anonymous:    false
            provider:     main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                secret:     %secret% # %secret% est un paramètre de parameter


    access_control:
        #- { path: ^/Connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY } #, requires_channel: https }
        #- { path: ^/, roles: ROLE_USER }