<?php

namespace LG\MyAEBundle\Repository;

/**
 * DevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisRepository extends \Doctrine\ORM\EntityRepository
{
}
